name: Build and Push Server Image

on:
  push:
    branches: [ "main" ] # Dispara sempre que houver push na main
    paths:
      - 'server/**' # Só dispara se houver mudanças na pasta do servidor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server # Indica que o Dockerfile está dentro de /server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chegaja-server:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}